version: '3'
services:
    healthforecast_app:
        container_name: healthforecast_app
        image: teodora95/healthforecastservice
        restart: on-failure
        ports: 
            - 10555:8080
        environment:
            WAIT_HOST: mysql:3306
        depends_on:
            - docker-mysql
    docker-mysql:
        container_name: docker-mysql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: healthforecast
            MYSQL_ROOT_PASSWORD: Teodora1!
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports: 
            - 6666:3306
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=Teodora1 --execute \"SHOW DATABASES \""
            interval: 4s
            timeout: 20s
            retries: 5